// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/cards/delete': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cards/delete').default>>>>
    }
    '/api/cards': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cards/index').default>>>>
    }
    '/api/cards/store': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cards/store').default>>>>
    }
    '/api/groceryList/delete': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryList/delete').default>>>>
    }
    '/api/groceryList/favorite': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryList/favorite').default>>>>
    }
    '/api/groceryList': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryList/index').default>>>>
    }
    '/api/groceryList/share': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryList/share').default>>>>
    }
    '/api/groceryList/store': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryList/store').default>>>>
    }
    '/api/groceryListItem/checked': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryListItem/checked').default>>>>
    }
    '/api/groceryListItem/decrease': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryListItem/decrease').default>>>>
    }
    '/api/groceryListItem/delete': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryListItem/delete').default>>>>
    }
    '/api/groceryListItem/increase': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryListItem/increase').default>>>>
    }
    '/api/groceryListItem': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryListItem/index').default>>>>
    }
    '/api/groceryListItem/store': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceryListItem/store').default>>>>
    }
    '/api/user/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/login').default>>>>
    }
    '/api/user/register': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/register').default>>>>
    }
    '/api/utils/apiClient': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/utils/apiClient').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}